apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: docker-registry.punqit.com/nodejs/punqit_frontend
      context: react
  tagPolicy:
    gitCommit:
  local:
    useBuildkit: true

deploy:
  kubectl:
    manifests:
    - k8s/*
